/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarEllipsis: typeof import('@varlet/ui')['_EllipsisComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTooltip: typeof import('@varlet/ui')['_TooltipComponent']
  }
}
